services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sigi_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT:-10000}:10000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sigi_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
