name: SIGI-A
values:
  - key: base_url
    value: 'http://localhost:8000'
    type: default
    enabled: true
  - key: token
    value: ''
    type: secret
    enabled: true
  - key: correo_login
    value: 'juan@example.com'
    type: default
    enabled: true
  - key: password_demo
    value: '123456'
    type: secret
    enabled: true
  - key: correo_2fa
    value: ''
    type: default
    enabled: true
  - key: codigo_2fa
    value: ''
    type: default
    enabled: true
  - key: rol_default
    value: 'negocio'
    type: default
    enabled: true
  - key: id_usuario
    value: ''
    type: default
    enabled: true
  - key: id_negocio
    value: ''
    type: default
    enabled: true
  - key: id_empleado
    value: ''
    type: default
    enabled: true
  - key: id_servicio
    value: ''
    type: default
    enabled: true
  - key: id_producto
    value: ''
    type: default
    enabled: true
  - key: id_pedido
    value: ''
    type: default
    enabled: true
  - key: id_pago
    value: ''
    type: default
    enabled: true
  - key: id_cita
    value: '1'
    type: default
    enabled: true
  - key: id_notificacion
    value: ''
    type: default
    enabled: true
  - key: id_carrito
    value: ''
    type: default
    enabled: true
  - key: id_favorito
    value: ''
    type: default
    enabled: true
